name: clang
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-ci-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-19 clang++-19 clang-format-19 clang-tidy-19 cppcheck doxygen libgl-dev libwayland-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev wayland-protocols
      - name: Set execute permission for CI script
        run: chmod +x ci/run-ci-clang.sh
      - name: Run CI Script
        run: ./ci/run-ci-clang.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        