name: gcc
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-ci-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen lcov libgl-dev libwayland-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev python3 python3-pip wayland-protocols xvfb
          pip3 install junit2html
      - name: Set execute permission for CI script
        run: chmod +x ci/run-ci-gcc.sh
      - name: Run CI Script with Xvfb
        run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./ci/run-ci-gcc.sh
      - name: Upload API Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/html/
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build-ci-gcc/coverage-html/
      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: build-ci-gcc/test_report.html
