name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-19 clang++-19 clang-format-19 clang-tidy-19

      - name: Set execute permission for CI script
        run: chmod +x run-ci.sh

      - name: Run CI Script
        run: ./run-ci.sh
        
      - name: Check for formatting changes
        run: |
          if ! git diff --quiet; then
            echo "Detected formatting changes, committing..."
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Apply clang-format fixes"
            git push
          else
            echo "No formatting changes detected."
          fi
        